config/routes.rb
SampleApp::Application.routes.draw do

  get "sessions/new"

  	resources :users do
      collection { post :uploadFile }
   end
   
   resources :sessions, :only => [:new, :create, :destroy]

	match '/signup', :to => 'users#new'
	match '/signin',  :to => 'sessions#new'
  	match '/signout', :to => 'sessions#destroy'
    

	get "pages/home"
	get "pages/contact"
	get "pages/about"
	match '/contact', :to => 'pages#contact'
	match '/about',   :to => 'pages#about'
	match '/help',    :to => 'pages#help'

	root :to => 'pages#home'

end

app/models/user.rb
#!/bin/env ruby
#encoding: utf-8

# == Schema Information
#
# Table name: users
#
#  id                 :integer          not null, primary key
#  nom                :string(255)
#  email              :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  encrypted_password :string(255)
#  salt               :string(255)
#  poids              :integer
#  poids_ideal        :integer
#  date               :text
#  fumeur             :boolean
#  aret               :boolean
#  taille             :integer
#  admin              :boolean          default(FALSE)
#

require 'digest'
class User < ActiveRecord::Base
	
	attr_accessor :password
	attr_accessible :id, :nom, :email, :password, :password_confirmation, :poids, :poids_ideal, :date, :taille, :fumeur, :aret
	
	email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	date_regex = /^(19|20)\d\d([- \.])(0[1-9]|1[012])\2(0[1-9]|[12][0-9]|3[01])$/i
	
	validates :nom, :presence => true,
						 :length => { :maximum => 50 }
						 
	validates :email, :presence => true,
                     :format   => { :with => email_regex },
                     :uniqueness => { :case_sensitive => false }
                     
  	# Crée automatique l'attribut virtuel 'password_confirmation'.
  	validates :password, :presence     => true,
                      	:confirmation => true,
                      	:length       => { :within => 6..40 }
 	
 	validates :poids, :presence => true
 	
 	validates :poids_ideal, :presence => true
   
   validates :date, :presence => true,
   			 		  :format => { :with => date_regex}
   			 		  
   validates :taille, :presence => true
   
	before_save :encrypt_password,
					:test_poids?
	
	def self.save_cv(upload,id)
    name =  "cv.pdf"
    
    if File.exists?("public/uploads/" + id[0].to_s) == false
    	Dir.mkdir("public/uploads/" + id[0].to_s)
    end
    
    directory = "public/uploads/" + id[0].to_s
    
    if File.exists?("public/uploads/" + id[0].to_s+"/cv.pdf") == true
    	File.delete("public/uploads/" + id[0].to_s+"/cv.pdf")
    end
    
    # create the file path
    path = File.join(directory, name)
    # write the file
    File.open(path, "wb") { |f| f.write(upload['datafile'].read) }
  end
  
  def hasCV?
  	return File.exists?("public/uploads/" + self.id.to_s+"/cv.pdf")
  end
	
	def age
		test = (Date.today - Date.parse(self.date)).to_i
		test = test/365
		return test
	end
	
	def calcul_imc
		poids = self.poids.to_f
		taille = self.taille.to_f
		imc = poids/((taille/100)*(taille/100))
		return imc
	end
	
	def test_poids?
		if self.poids.to_i < self.poids_ideal.to_i
			errors.add(:poids," : doit être supérieur au poids idéal")
			return false
		end
		return true
	end
	
	def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil  if user.nil?
    return user if user.has_password?(submitted_password)
  end

  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end
	
	# Retour true (vrai) si le mot de passe correspond.
	
	def has_password?(password_soumis)
		encrypted_password == encrypt(password_soumis)
	end
	
	def self.authenticate(email, submitted_password)
    	user = find_by_email(email)
    	return nil  if user.nil?
    	return user if user.has_password?(submitted_password)
  	end
	
	private
	
	def encrypt_password
		self.salt = make_salt if new_record?
		self.encrypted_password = encrypt(password)
	end
	
	def encrypt(string)
		secure_hash("#{salt}--#{string}")
	end
	
	def make_salt
		secure_hash("#{Time.now.utc}--#{password}")
	end

	def secure_hash(string)
		Digest::SHA2.hexdigest(string)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @titre = "Accueil"
  end

  def contact
    @titre = "Contact"
  end

  def about
    @titre = "A Propos"
  end

	def help
		@titre = "Aide"
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @titre = "S'identifier"
  end

  def create
  	 user = User.authenticate(params[:session][:email],
                             params[:session][:password])
    if user.nil?
      flash.now[:error] = "Combinaison Email/Mot de passe invalide."
      @titre = "S'identifier"
      render 'new'
    else
      sign_in user
      redirect_back_or user
    end
  end

  def destroy
  	sign_out
   redirect_to root_path
  end

end

app/controllers/users_controller.rb
#!/bin/env ruby
#encoding: utf-8

class UsersController < ApplicationController
  before_filter :authenticate, :only => [:index, :edit, :update, :destroy]
  before_filter :correct_user, :only => [:edit, :update]
  before_filter :admin_user,   :only => :destroy
  
  def index
    @titre = "Liste des utilisateurs"
    @users = User.paginate(:page => params[:page])
  end
  
  def show
    @user = User.find(params[:id])
    @titre = @user.nom
  end
  
  def new
  	@user = User.new
  	@titre = "Inscription"
  end
  
  def edit
    @titre = "Édition profil"
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
    	sign_in @user
    	flash[:success] = "Bienvenue dans l'Application Exemple!"
    	redirect_to @user
    else
      @titre = "Inscription"
      render 'new'
    end
  end
  
	def uploadFile
    post = User.save_cv(params[:upload], params[:id].keys)
    @user = User.find(params[:id].keys)
    redirect_to @user
	end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Profil actualisé."
      redirect_to @user
    else
      @titre = "Édition profil"
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "Utilisateur supprimé."
    redirect_to users_path
  end
  
  private
	  
	  def authenticate
		   deny_access unless signed_in?
	  end
	  
	  def correct_user
		   @user = User.find(params[:id])
		   redirect_to(root_path) unless current_user?(@user)
	  end
	  
	  def admin_user
      redirect_to(root_path) unless current_user.admin?
     end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def logo
		logo = image_tag("logo.png", :alt => "Application exemple", :class => "round")
	end

  #Retourner un titre basé sur la page
  def titre
    base_titre = "Simple App du Tutoriel Ruby on Rails"
    if @titre.nil?
      base_titre
    else
      "#{base_titre} | #{@titre}"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
   	cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    	self.current_user = user
  	end
  	
  	def current_user=(user)
    @current_user = user
  	end
  	
  	def current_user
    @current_user ||= user_from_remember_token
  	end
	
	def signed_in?
    !current_user.nil?
  	end
  	
  	def sign_out
    cookies.delete(:remember_token)
    self.current_user = nil
  	end
  	
  	def current_user?(user)
    user == current_user
  	end
  	
  	def deny_access
    store_location
    redirect_to signin_path, :notice => "Please sign in to access this page."
  	end

  	def redirect_back_or(default)
  	 redirect_to(session[:return_to] || default)
    clear_return_to
  	end
  	
  private

    def user_from_remember_token
      User.authenticate_with_salt(*remember_token)
    end

    def remember_token
      cookies.signed[:remember_token] || [nil, nil]
    end
    
    def store_location
      session[:return_to] = request.fullpath
    end

    def clear_return_to
      session[:return_to] = nil
    end

end

app/helpers/users_helper.rb
module UsersHelper

	def gravatar_for(user, options = { :size => 50 })
		gravatar_image_tag(user.email.downcase, :alt => user.nom,
                                      :class => 'gravatar',
                                      :gravatar => options)
	end
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "A Propos", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
      <li><a href="http://www.railstutorial.org/">Tutoriel Rails</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
	<%= link_to logo, root_path %>
	<nav class="round">
		<ul>
			<li><%= link_to "Accueil", root_path %></li>
			<li><%= link_to "Aide", help_path %></li>
			<% if signed_in? %>
				<li><%= link_to "Utilisateurs", users_path %></li>
				<li><%= link_to "Profil", current_user %></li>
				<li><%= link_to "Réglages", edit_user_path(current_user) %></li>
		   <% end %>
			<% if signed_in? %>
		   	<li><%= link_to "Déconnexion", signout_path, :method => :delete %></li>
		   <% else %>
		   	<li><%= link_to "S'identifier", signin_path %></li>
		   <% end %>
		</ul>
	</nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= titre %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
    <%= javascript_include_tag :defaults %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <section class="round">
      	<% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>
  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  est un projet de livre et de screencasts pour apprendre le développement web
  avec <a href="http://rubyonrails.org/">Ruby on Rails</a>. C'est l'Application Exemple de ce tutoriel.
</p>

app/views/pages/contact.html.erb
<h1>Contact</h1>
<p>
  Contact du Tutoriel Ruby on Rails à propos de l'Application Exemple à la
  <a href="http://railstutorial.org/feedback">page de feedback</a>.
</p>

app/views/pages/help.html.erb
<h1>Aide</h1>
<p>
  Obtenez de l'aide sur le Tutoriel Ruby on Rails Tutorial sur la
  <a href="http://railstutorial.org/help">page d'aide du Tutoriel Rails</a>.
  Pour obtenir de l'aide sur cette application exemple, consultez le
  <a href="http://railstutorial.org/book">livre du Tutoriel Rails</a>.
</p>

app/views/pages/home.html.erb
<h1>Tabaco Fight</h1>
		<p>
		Venez prendre part au combat entre les fumeurs et les non fumeurs!<br />
		Inscrivez vous et participez à des batailles épiques! <br />
		Attention cependant, il existe une classe particulière, les fumeurs voulant 			arêter de fumer, ce sont des espions utilisez les avec méfiance, personne ne 			peut savoir dans quel camp ils sont ...
		</p>
		<% if !signed_in? %>
			<%= link_to "S'inscrire !", signup_path, :class => "signup_button round" %>
		<% end %>
		<br />
	<h4>Pour le camp des fumeurs je nomme</h4>
		<% User.all.each do |user| %>
			<% if user.fumeur? && !user.aret? %>
				<%= link_to gravatar_for(user, :size => 37, :alt => user),user %>
			<% end %>
	  	<% end %>
	<br />
	<br />
	<h4>Pour le camp des non fumeurs je nomme</h4>
	<% User.all.each do |user| %>
		<% if !user.fumeur? %>
			<%= link_to gravatar_for(user, :size => 37, :alt => user),user %>
	  	<% end %>
	<% end %>
	
	<h4>Pour le camp des espions je nomme</h4>
	<% User.all.each do |user| %>
		<% if user.aret? %>
			<%= link_to gravatar_for(user, :size => 37, :alt => user),user %>
	  	<% end %>
	<% end %>
<br />
<br />
<br />
<br />

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> 
        prohibited this <%= object.class.to_s.underscore.humanize.downcase %> 
        from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, :size => 30 %>
  <%= link_to user.nom, user %>
  <% if current_user.admin? %>
  | <%= link_to "supprimer", user, :method => :delete, :confirm => "Etes-vous certain&nbsp;?",
                                :title => "Supprimer #{user.nom}" %>
  <% end %>
</li>

app/views/users/edit.html.erb
<script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
<script>
  $(function(){
    var mySpan = $("#hid").hide();
    $("#user_fumeur").click(function(){
      if($(this).is(":checked"))
        mySpan.show();
      else
        mySpan.hide();
    });
  });
</script>


<h1>Edition du profil</h1>

<%= form_for(@user) do |f| %>
	<%= render 'shared/error_messages', :object => f.object %>
	<div class="field">
	 <%= f.label :nom %><br />
	 <%= f.text_field :nom %>
	</div>
	<div class="field">
	 <%= f.label :date, "Date de naissance (format : yyyy-mm-dd)" %><br />
	 <%= f.text_field :date %>
	</div>
	<div class="field">
	 <%= f.label :poids, "Poids actuel (en Kg)" %><br />
	 <%= f.text_field :poids %>
	</div>
	<div class="field">
	 <%= f.label :poids_ideal, "Poids idéal (en Kg)" %><br />
	 <%= f.text_field :poids_ideal %>
	</div>
	<div class="field">
	 <%= f.label :taille, "Taille (en cm)" %><br />
	 <%= f.text_field :taille %>
	</div>
	<div class="field">
	 <span><%= f.label :fumeur, "fumeur ?" %><%= f.check_box :fumeur %></span>
	 <span id="hid"><%= f.label :aret, "j'aimerais arêter ?" %><%= f.check_box :aret %></span>
	</div>
	<div class="field">
	 <%= f.label :email %><br />
	 <%= f.text_field :email %>
	</div>
	<div class="field">
	 <%= f.label :password %><br />
	 <%= f.password_field :password %>
	</div>
	<div class="field">
	 <%= f.label :password_confirmation, "Confirmation" %><br />
	 <%= f.password_field :password_confirmation %>
	</div>
	<div class="actions">
	 <%= f.submit "Actualiser" %>
	</div>  
	<% end %>
<br />
<div>
  <%= gravatar_for @user %>
  <a href="http://gravatar.com/emails">changer</a>
</div>
<br />
<br />
<br />
<br />

app/views/users/index.html.erb
<h1>Liste des utilisateurs</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<table class="profile" summary="Information profil">
  <tr>
    <td class="main">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.nom %>
      </h1>
    </td>
    <td class="sidebar round">
    	<strong>Camp</strong> <% if @user.fumeur? && !@user.aret?%> Fumeur <% else %> <% if @user.fumeur? && @user.aret? %> Epsion <% else %> Non Fumeur  <%end %><%end %><br />
      <strong>Nom</strong> <%= @user.nom %><br />
      <strong>URL</strong>  <%= link_to user_path(@user), @user %><br />
      <strong>Poids actuel</strong> <%= @user.poids %><br />
		<strong>Poids idéal</strong> <%= @user.poids_ideal %><br />
		<strong>Age</strong> <%= @user.age %><br />
		<strong>Imc</strong> <%= @user.calcul_imc %><br />
		<% if @user.hasCV? %>
		<strong>CV</strong> <%= link_to 'lien vers le cv','/uploads/' + @user.id.to_s + '/cv.pdf'%>
		<% else %>
			<strong>CV</strong> aucun CV uploadé
		<% end %>
    </td>
  </tr>  
</table>

<% if signed_in? && current_user.nom == @user.nom %>
	<%= form_tag({:action => 'uploadFile'}, :multipart => true) do %>
		<p><label for="upload_file">Sélectionnez votre CV</label><br />
		<%= file_field 'upload', 'datafile' %>
		<%= hidden_field 'id' , @user.id %>	<%= submit_tag "Upload" %></p>
	<% end %>
<% end %>